name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build .app with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller --windowed --name easy-see main.py

    - name: Compress .app and create .dmg
      run: |
        mkdir dist/final
        cp -R dist/easy-see.app dist/final/
        hdiutil create -volname EasySee -srcfolder dist/final -ov -format UDZO dist/easy-see.dmg
        zip -r dist/easy-see.app.zip dist/easy-see.app

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: easy-see-mac
        path: |
          dist/easy-see.dmg
          dist/easy-see.app.zip
