name: Build macOS App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build with py2app
        run: |
          python3 setup.py py2app

      - name: List build output
        run: |
          ls -al dist/

      - name: Create DMG
        run: |
          hdiutil create -volname easy-see -srcfolder dist/main.app -ov -format UDZO dist/easy-see.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: easy-see-mac
          path: |
            dist/easy-see.dmg
            dist/main.app
