name: Build macOS EasySee App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build .app
        run: |
          source venv/bin/activate
          python setup.py py2app

      - name: Zip the .app
        run: |
          cd dist
          zip -r main.app.zip main.app

      - name: Build .dmg
        run: |
          hdiutil create -volname EasySee -srcfolder dist/main.app -ov -format UDZO EasySee.dmg

      - name: Upload built files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: easysee-macos
          path: |
            dist/main.app.zip
            EasySee.dmg
