name: Build Mac App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Zip the .app
        run: |
          cd dist
          zip -r main.app.zip main.app

      - name: Create .dmg
        run: |
          hdiutil create -volname easy-see -srcfolder dist/main.app -ov -format UDZO dist/easy-see.dmg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: easy-see-mac
          path: |
            dist/main.app.zip
            dist/easy-see.dmg
