name: Build macOS App with PyInstaller

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build .app with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller main.py --noconfirm --windowed --onefile --name easy-see

    - name: Create .dmg installer
      run: |
        mkdir -p dmg-staging
        cp dist/easy-see dmg-staging/
        hdiutil create easy-see.dmg -volname "EasySee" -srcfolder dmg-staging -ov -format UDZO

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: easy-see-macos
        path: |
          dist/easy-see
          easy-see.dmg
