name: Build macOS EasySee App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build .app with py2app
      run: |
        source venv/bin/activate
        python setup.py py2app

    - name: Zip the .app bundle
      run: |
        cd dist
        zip -r main.app.zip main.app

    - name: Build .dmg installer
      run: |
        hdiutil create -volname EasySee \
          -srcfolder dist/main.app \
          -ov -format UDZO EasySee.dmg

    - name: Create GitHub Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        name: "EasySee for macOS"
        tag_name: "v1.0"
        files: |
          dist/main.app.zip
          EasySee.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
