name: Build macOS App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}  # <-- 添加这一行，允许从 GitHub 界面手动触发构建

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app with py2app
        run: |
          source venv/bin/activate
          python3 setup.py py2app

      - name: Zip the .app bundle
        run: |
          cd dist
          # 使用 ditto 压缩 .app 更适合 mac 应用包
          ditto -c -k --sequesterRsrc --keepParent main.app ../main.app.zip

      - name: Create .dmg installer
        run: |
          hdiutil create -volname easy-see -srcfolder dist/main.app -ov -format UDZO dist/easy-see.dmg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: easy-see-macos
          path: |
            dist/main.app.zip
            dist/easy-see.dmg
