name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 手动触发支持

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller --noconfirm --windowed --clean --name easy-see main.py

    - name: Create DMG
      run: |
        mkdir -p dmg
        cp -R dist/easy-see.app dmg/
        hdiutil create easy-see.dmg -volname "EasySee" -srcfolder dmg -ov -format UDZO

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: easy-see-mac
        path: |
          dist/easy-see.app
          easy-see.dmg
